### ISSUE TITLE
DNS resolution ignores entries in /etc/hosts file

### ISSUE THREAD

**Issue by mkhurramali** [serviejs/popsicle-transport-http#6]
In previous versions (1.0.9) entries in /etc/hosts file were used during dns resolution. Now (1.1.1), those entries are being ignored.

**Comment by blakeembrey** [comment]
Thanks for the report! I started using DNS entry caching and it’s meant to be supporting according to this issue: https://github.com/szmarczak/cacheable-lookup/issues/8. I’ll play around locally and confirm, sorry about this regression.

**Comment by blakeembrey** [comment]
Just looked through the code, it looks like it's using `dns.resolve` first and then falling back to `dns.lookup`. The reason to do this is likely around `dns.lookup` considerations (https://nodejs.org/api/dns.html#dns_implementation_considerations):

> Though the call to dns.lookup() will be asynchronous from JavaScript's perspective, it is implemented as a synchronous call to getaddrinfo(3) that runs on libuv's threadpool. This can have surprising negative performance implications for some applications, see the UV_THREADPOOL_SIZE documentation for more information.

I'm happy to revert this change, did not realize it would be a breaking change 😓

**Comment by blakeembrey** [comment]
Reverted in https://github.com/serviejs/popsicle-transport-http/releases/tag/v1.1.2.

**Comment by mkhurramali** [comment]
@blakeembrey thank you so much for your help sorting this out!
